### ISSUE TITLE
Oceanic Remains don't spawn at all (1.19.2)

### ISSUE THREAD

**Issue by CrystalZink** [Nyancatpig/Modest-Mining-1.19#1]
Oceanic Remains don't seem to spawn in the latest version, after skimming through the mod i found out that the **"add_oceanic_remains"** json is completely missing from the **forge/biome_modifier** folders

That and bundled with a /fill command test replacing any potential oceanic remain blocks with air, around 30k blocks worth and no block was found, hope this helps!

**Comment by Nyancatpig** [comment]
this should now be fixed :)
