### ISSUE TITLE
Copper nuggets are broken

### ISSUE THREAD

**Issue by itsdeadfrosty** [Nyancatpig/Modest-Mining-1.19#2]
copper nuggets covert into ingots in crafting table at a rate of 1:1, super imbalanced 

theres also no configs? why?

**Comment by Nyancatpig** [comment]
yep that’s definitely a bug

as for configs, i simply haven’t gotten around to them
what would you suggest be configurable?

**Comment by itsdeadfrosty** [comment]
good question, maybe enabling the hatchets to be used to directly convert plant matter to fiber on block break, instead of in the crafting table? idk its just most mods have configs to enable or disable features.
