### ISSUE TITLE
Pearls are unobtainable due to tag error

### ISSUE THREAD

**Issue by CrystalZink** [Nyancatpig/Modest-Mining-1.19#3]
Tried killing tons of clams with a chisel, none dropped pearls
Checked thru the files to notice that the tag used for the chisels is outdated, as it features the weathered chisels which were removed

can be fixed by either editing the tag in **clam.json** by making it just **"item": "modestmining:chisel"**, or by just updating the "chisels" tag to include the normal chisel (for whatever reason lol, thats just a free file nuke at that point)

**Comment by Nyancatpig** [comment]
I knew I’d forgotten something! Thankyou for your report.
